import type { Category, FridgeArea, FridgeModel, ShelfLifePreset } from '@/types';

// 预设分类
export const presetCategories: Category[] = [
  { id: 'cat-vegetable', name: '蔬菜', nameEn: 'Vegetables', icon: '🥬', color: '#22c55e', defaultShelfLife: { fridge: 5, freezer: 30, fresh: 3 }, sortOrder: 1, isPreset: true },
  { id: 'cat-fruit', name: '水果', nameEn: 'Fruits', icon: '🍎', color: '#ef4444', defaultShelfLife: { fridge: 7, freezer: 30, fresh: 5 }, sortOrder: 2, isPreset: true },
  { id: 'cat-meat', name: '肉类', nameEn: 'Meat', icon: '🥩', color: '#dc2626', defaultShelfLife: { fridge: 3, freezer: 90, fresh: 2 }, sortOrder: 3, isPreset: true },
  { id: 'cat-seafood', name: '海鲜', nameEn: 'Seafood', icon: '🦐', color: '#0ea5e9', defaultShelfLife: { fridge: 2, freezer: 60, fresh: 1 }, sortOrder: 4, isPreset: true },
  { id: 'cat-dairy', name: '乳制品', nameEn: 'Dairy', icon: '🥛', color: '#f8fafc', defaultShelfLife: { fridge: 7, freezer: 30, fresh: 5 }, sortOrder: 5, isPreset: true },
  { id: 'cat-drink', name: '饮品', nameEn: 'Drinks', icon: '🥤', color: '#3b82f6', defaultShelfLife: { fridge: 14, freezer: 30, fresh: 7 }, sortOrder: 6, isPreset: true },
  { id: 'cat-sauce', name: '调味品', nameEn: 'Condiments', icon: '🧂', color: '#a855f7', defaultShelfLife: { fridge: 30, freezer: 90, fresh: 14 }, sortOrder: 7, isPreset: true },
  { id: 'cat-cooked', name: '熟食/剩菜', nameEn: 'Cooked/Leftovers', icon: '🍱', color: '#f97316', defaultShelfLife: { fridge: 3, freezer: 30, fresh: 2 }, sortOrder: 8, isPreset: true },
  { id: 'cat-frozen', name: '冷冻食品', nameEn: 'Frozen Food', icon: '🧊', color: '#06b6d4', defaultShelfLife: { fridge: 1, freezer: 90, fresh: 0 }, sortOrder: 9, isPreset: true },
  { id: 'cat-bakery', name: '面食/烘焙', nameEn: 'Bakery', icon: '🍞', color: '#d97706', defaultShelfLife: { fridge: 5, freezer: 30, fresh: 3 }, sortOrder: 10, isPreset: true },
  { id: 'cat-egg', name: '蛋类', nameEn: 'Eggs', icon: '🥚', color: '#fbbf24', defaultShelfLife: { fridge: 21, freezer: 0, fresh: 14 }, sortOrder: 11, isPreset: true },
  { id: 'cat-canned', name: '罐头/腌制', nameEn: 'Canned/Pickled', icon: '🫙', color: '#78716c', defaultShelfLife: { fridge: 180, freezer: 180, fresh: 90 }, sortOrder: 12, isPreset: true },
  { id: 'cat-other', name: '其他', nameEn: 'Other', icon: '📦', color: '#6b7280', defaultShelfLife: { fridge: 7, freezer: 30, fresh: 5 }, sortOrder: 13, isPreset: true },
];

// 预设冰箱区域
export const presetAreas: FridgeArea[] = [
  { id: 'area-fridge', name: '冷藏室', nameEn: 'Fridge', icon: '🧊', temperature: 4, sortOrder: 1, isPreset: true },
  { id: 'area-freezer', name: '冷冻室', nameEn: 'Freezer', icon: '❄️', temperature: -18, sortOrder: 2, isPreset: true },
  { id: 'area-fresh', name: '保鲜层/果蔬盒', nameEn: 'Crisper', icon: '🌡️', temperature: 2, sortOrder: 3, isPreset: true },
  { id: 'area-door', name: '门架', nameEn: 'Door', icon: '🚪', temperature: 5, sortOrder: 4, isPreset: true },
];

// 预设冰箱型号
export const presetFridgeModels: FridgeModel[] = [
  {
    id: 'model-single', name: '单门小冰箱', nameEn: 'Mini Fridge', icon: '🧊',
    description: '适合单人/宿舍，冷藏+微冻', descriptionEn: 'For singles/dorm, fridge + chill',
    zones: [
      { id: 'z-single-upper', name: '上层冷藏', nameEn: 'Upper Fridge', icon: '🧊', type: 'fridge', row: 0, col: 0, temperature: 4 },
      { id: 'z-single-lower', name: '下层微冻', nameEn: 'Lower Chill', icon: '🌡️', type: 'fresh', row: 1, col: 0, temperature: 0 },
      { id: 'z-single-door', name: '门架', nameEn: 'Door', icon: '🚪', type: 'door', row: 0, col: 1, temperature: 5 },
    ],
  },
  {
    id: 'model-double', name: '双门冰箱', nameEn: 'Double Door', icon: '🧊',
    description: '常见家用，上冷藏下冷冻', descriptionEn: 'Common household, fridge on top, freezer below',
    zones: [
      { id: 'z-dbl-fridge', name: '冷藏室', nameEn: 'Fridge', icon: '🧊', type: 'fridge', row: 0, col: 0, temperature: 4 },
      { id: 'z-dbl-fresh', name: '果蔬盒', nameEn: 'Crisper', icon: '🌡️', type: 'fresh', row: 1, col: 0, temperature: 2 },
      { id: 'z-dbl-door', name: '门架', nameEn: 'Door', icon: '🚪', type: 'door', row: 0, col: 1, temperature: 5 },
      { id: 'z-dbl-freezer', name: '冷冻室', nameEn: 'Freezer', icon: '❄️', type: 'freezer', row: 2, col: 0, temperature: -18 },
    ],
  },
  {
    id: 'model-triple', name: '三门冰箱', nameEn: 'Triple Door', icon: '🧊',
    description: '冷藏+变温+冷冻三区独立', descriptionEn: 'Fridge + variable + freezer, 3 zones',
    zones: [
      { id: 'z-tri-fridge', name: '冷藏室', nameEn: 'Fridge', icon: '🧊', type: 'fridge', row: 0, col: 0, temperature: 4 },
      { id: 'z-tri-door', name: '门架', nameEn: 'Door', icon: '🚪', type: 'door', row: 0, col: 1, temperature: 5 },
      { id: 'z-tri-fresh', name: '变温室', nameEn: 'Variable Zone', icon: '🌡️', type: 'fresh', row: 1, col: 0, temperature: 0 },
      { id: 'z-tri-freezer', name: '冷冻室', nameEn: 'Freezer', icon: '❄️', type: 'freezer', row: 2, col: 0, temperature: -18 },
    ],
  },
  {
    id: 'model-side-by-side', name: '对开门冰箱', nameEn: 'Side by Side', icon: '🧊',
    description: '左冷冻右冷藏，大容量', descriptionEn: 'Freezer left, fridge right, large capacity',
    zones: [
      { id: 'z-sbs-fridge', name: '冷藏区', nameEn: 'Fridge Zone', icon: '🧊', type: 'fridge', row: 0, col: 1, temperature: 4 },
      { id: 'z-sbs-door', name: '门架', nameEn: 'Door', icon: '🚪', type: 'door', row: 0, col: 2, temperature: 5 },
      { id: 'z-sbs-fresh', name: '果蔬盒', nameEn: 'Crisper', icon: '🌡️', type: 'fresh', row: 1, col: 1, temperature: 2 },
      { id: 'z-sbs-freezer', name: '冷冻区', nameEn: 'Freezer Zone', icon: '❄️', type: 'freezer', row: 0, col: 0, temperature: -18 },
    ],
  },
  {
    id: 'model-cross', name: '十字门冰箱', nameEn: 'Cross Door', icon: '🧊',
    description: '上对开冷藏+下双抽冷冻', descriptionEn: 'Top fridge doors + bottom freezer drawers',
    zones: [
      { id: 'z-cross-fridge', name: '上层冷藏', nameEn: 'Upper Fridge', icon: '🧊', type: 'fridge', row: 0, col: 0, temperature: 4 },
      { id: 'z-cross-door', name: '门架', nameEn: 'Door', icon: '🚪', type: 'door', row: 0, col: 1, temperature: 5 },
      { id: 'z-cross-fresh', name: '果蔬抽屉', nameEn: 'Crisper Drawer', icon: '🌡️', type: 'fresh', row: 1, col: 0, temperature: 2 },
      { id: 'z-cross-freezer-l', name: '左冷冻抽屉', nameEn: 'Left Freezer', icon: '❄️', type: 'freezer', row: 2, col: 0, temperature: -18 },
      { id: 'z-cross-freezer-r', name: '右冷冻抽屉', nameEn: 'Right Freezer', icon: '❄️', type: 'freezer', row: 2, col: 1, temperature: -18 },
    ],
  },
];

// 预设保质期数据库 (200+)
export const presetShelfLives: ShelfLifePreset[] = [
  // 蔬菜类
  { id: 'sl-1', foodName: '白菜', foodNameEn: 'Chinese Cabbage', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-2', foodName: '菠菜', foodNameEn: 'Spinach', categoryId: 'cat-vegetable', shelfLife: { fridge: 4, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-3', foodName: '生菜', foodNameEn: 'Lettuce', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-4', foodName: '西兰花', foodNameEn: 'Broccoli', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 4, room: 2 }, source: 'preset' },
  { id: 'sl-5', foodName: '胡萝卜', foodNameEn: 'Carrot', categoryId: 'cat-vegetable', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 5 }, source: 'preset' },
  { id: 'sl-6', foodName: '土豆', foodNameEn: 'Potato', categoryId: 'cat-vegetable', shelfLife: { fridge: 21, freezer: 30, fresh: 14, room: 7 }, source: 'preset' },
  { id: 'sl-7', foodName: '番茄', foodNameEn: 'Tomato', categoryId: 'cat-vegetable', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-8', foodName: '黄瓜', foodNameEn: 'Cucumber', categoryId: 'cat-vegetable', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-9', foodName: '茄子', foodNameEn: 'Eggplant', categoryId: 'cat-vegetable', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-10', foodName: '青椒', foodNameEn: 'Bell Pepper', categoryId: 'cat-vegetable', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-11', foodName: '洋葱', foodNameEn: 'Onion', categoryId: 'cat-vegetable', shelfLife: { fridge: 14, freezer: 30, fresh: 14, room: 7 }, source: 'preset' },
  { id: 'sl-12', foodName: '大蒜', foodNameEn: 'Garlic', categoryId: 'cat-vegetable', shelfLife: { fridge: 21, freezer: 30, fresh: 14, room: 7 }, source: 'preset' },
  { id: 'sl-13', foodName: '生姜', foodNameEn: 'Ginger', categoryId: 'cat-vegetable', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 5 }, source: 'preset' },
  { id: 'sl-14', foodName: '芹菜', foodNameEn: 'Celery', categoryId: 'cat-vegetable', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-15', foodName: '豆角', foodNameEn: 'Green Bean', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-16', foodName: '豌豆', foodNameEn: 'Peas', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-17', foodName: '玉米', foodNameEn: 'Corn', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-18', foodName: '蘑菇', foodNameEn: 'Mushroom', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-19', foodName: '豆芽', foodNameEn: 'Bean Sprouts', categoryId: 'cat-vegetable', shelfLife: { fridge: 3, freezer: 30, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-20', foodName: '韭菜', foodNameEn: 'Chives', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-21', foodName: '红薯', foodNameEn: 'Sweet Potato', categoryId: 'cat-vegetable', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 7 }, source: 'preset' },
  { id: 'sl-22', foodName: '南瓜', foodNameEn: 'Pumpkin', categoryId: 'cat-vegetable', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 14 }, source: 'preset' },
  { id: 'sl-23', foodName: '冬瓜', foodNameEn: 'Winter Melon', categoryId: 'cat-vegetable', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 7 }, source: 'preset' },
  { id: 'sl-24', foodName: '苦瓜', foodNameEn: 'Bitter Melon', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-25', foodName: '莲藕', foodNameEn: 'Lotus Root', categoryId: 'cat-vegetable', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-26', foodName: '油麦菜', foodNameEn: 'Romaine Lettuce', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-27', foodName: '空心菜', foodNameEn: 'Water Spinach', categoryId: 'cat-vegetable', shelfLife: { fridge: 4, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-28', foodName: '苋菜', foodNameEn: 'Amaranth', categoryId: 'cat-vegetable', shelfLife: { fridge: 4, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-29', foodName: '秋葵', foodNameEn: 'Okra', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-200', foodName: '山药', foodNameEn: 'Chinese Yam', categoryId: 'cat-vegetable', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 7 }, source: 'preset' },
  { id: 'sl-201', foodName: '芋头', foodNameEn: 'Taro', categoryId: 'cat-vegetable', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 7 }, source: 'preset' },
  { id: 'sl-202', foodName: '菜心', foodNameEn: 'Choy Sum', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-203', foodName: '芥兰', foodNameEn: 'Chinese Kale', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-204', foodName: '丝瓜', foodNameEn: 'Luffa', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-205', foodName: '木耳菜', foodNameEn: 'Malabar Spinach', categoryId: 'cat-vegetable', shelfLife: { fridge: 4, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-206', foodName: '荠菜', foodNameEn: 'Shepherd\'s Purse', categoryId: 'cat-vegetable', shelfLife: { fridge: 4, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-207', foodName: '香椿', foodNameEn: 'Toon Sprouts', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-208', foodName: '芦笋', foodNameEn: 'Asparagus', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  // 水果类
  { id: 'sl-30', foodName: '苹果', foodNameEn: 'Apple', categoryId: 'cat-fruit', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 7 }, source: 'preset' },
  { id: 'sl-31', foodName: '香蕉', foodNameEn: 'Banana', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-32', foodName: '橙子', foodNameEn: 'Orange', categoryId: 'cat-fruit', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 7 }, source: 'preset' },
  { id: 'sl-33', foodName: '柠檬', foodNameEn: 'Lemon', categoryId: 'cat-fruit', shelfLife: { fridge: 21, freezer: 30, fresh: 14, room: 7 }, source: 'preset' },
  { id: 'sl-34', foodName: '葡萄', foodNameEn: 'Grape', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-35', foodName: '草莓', foodNameEn: 'Strawberry', categoryId: 'cat-fruit', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-36', foodName: '蓝莓', foodNameEn: 'Blueberry', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-37', foodName: '西瓜', foodNameEn: 'Watermelon', categoryId: 'cat-fruit', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 3 }, source: 'preset' },
  { id: 'sl-38', foodName: '芒果', foodNameEn: 'Mango', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-39', foodName: '猕猴桃', foodNameEn: 'Kiwi', categoryId: 'cat-fruit', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 5 }, source: 'preset' },
  { id: 'sl-40', foodName: '桃子', foodNameEn: 'Peach', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-41', foodName: '梨', foodNameEn: 'Pear', categoryId: 'cat-fruit', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 5 }, source: 'preset' },
  { id: 'sl-42', foodName: '樱桃', foodNameEn: 'Cherry', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-43', foodName: '荔枝', foodNameEn: 'Lychee', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-44', foodName: '龙眼', foodNameEn: 'Longan', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-45', foodName: '柚子', foodNameEn: 'Pomelo', categoryId: 'cat-fruit', shelfLife: { fridge: 21, freezer: 30, fresh: 14, room: 14 }, source: 'preset' },
  { id: 'sl-46', foodName: '火龙果', foodNameEn: 'Dragon Fruit', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-47', foodName: '牛油果', foodNameEn: 'Avocado', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-48', foodName: '哈密瓜', foodNameEn: 'Hami Melon', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 5 }, source: 'preset' },
  { id: 'sl-49', foodName: '木瓜', foodNameEn: 'Papaya', categoryId: 'cat-fruit', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 3 }, source: 'preset' },
  { id: 'sl-50', foodName: '石榴', foodNameEn: 'Pomegranate', categoryId: 'cat-fruit', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 7 }, source: 'preset' },
  // 肉类
  { id: 'sl-60', foodName: '猪肉', foodNameEn: 'Pork', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-61', foodName: '牛肉', foodNameEn: 'Beef', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-62', foodName: '羊肉', foodNameEn: 'Lamb', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-63', foodName: '鸡肉', foodNameEn: 'Chicken', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-64', foodName: '鸭肉', foodNameEn: 'Duck', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-65', foodName: '排骨', foodNameEn: 'Ribs', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-66', foodName: '肉馅', foodNameEn: 'Ground Meat', categoryId: 'cat-meat', shelfLife: { fridge: 2, freezer: 60, fresh: 1, room: 1 }, source: 'preset' },
  { id: 'sl-67', foodName: '培根', foodNameEn: 'Bacon', categoryId: 'cat-meat', shelfLife: { fridge: 7, freezer: 60, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-68', foodName: '火腿', foodNameEn: 'Ham', categoryId: 'cat-meat', shelfLife: { fridge: 7, freezer: 60, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-69', foodName: '香肠', foodNameEn: 'Sausage', categoryId: 'cat-meat', shelfLife: { fridge: 7, freezer: 60, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-70', foodName: '腊肉', foodNameEn: 'Cured Meat', categoryId: 'cat-meat', shelfLife: { fridge: 14, freezer: 90, fresh: 7, room: 7 }, source: 'preset' },
  { id: 'sl-210', foodName: '五花肉', foodNameEn: 'Pork Belly', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-211', foodName: '里脊肉', foodNameEn: 'Pork Loin', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-212', foodName: '猪蹄', foodNameEn: 'Pork Trotters', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-213', foodName: '猪耳', foodNameEn: 'Pork Ear', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-214', foodName: '牛排', foodNameEn: 'Steak', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-215', foodName: '牛腩', foodNameEn: 'Beef Brisket', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-216', foodName: '牛腱', foodNameEn: 'Beef Shank', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-217', foodName: '牛尾', foodNameEn: 'Oxtail', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-218', foodName: '羊腿', foodNameEn: 'Lamb Leg', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-219', foodName: '羊排', foodNameEn: 'Lamb Chops', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-220', foodName: '鸡翅', foodNameEn: 'Chicken Wings', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-221', foodName: '鸡胸肉', foodNameEn: 'Chicken Breast', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-222', foodName: '鸡腿', foodNameEn: 'Chicken Leg', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-223', foodName: '鸡爪', foodNameEn: 'Chicken Feet', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-224', foodName: '鹅肉', foodNameEn: 'Goose', categoryId: 'cat-meat', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  // 海鲜类
  { id: 'sl-80', foodName: '鱼', foodNameEn: 'Fish', categoryId: 'cat-seafood', shelfLife: { fridge: 2, freezer: 60, fresh: 1, room: 1 }, source: 'preset' },
  { id: 'sl-81', foodName: '虾', foodNameEn: 'Shrimp', categoryId: 'cat-seafood', shelfLife: { fridge: 2, freezer: 60, fresh: 1, room: 1 }, source: 'preset' },
  { id: 'sl-82', foodName: '螃蟹', foodNameEn: 'Crab', categoryId: 'cat-seafood', shelfLife: { fridge: 2, freezer: 60, fresh: 1, room: 1 }, source: 'preset' },
  { id: 'sl-83', foodName: '贝类', foodNameEn: 'Shellfish', categoryId: 'cat-seafood', shelfLife: { fridge: 2, freezer: 60, fresh: 1, room: 1 }, source: 'preset' },
  { id: 'sl-84', foodName: '鱿鱼', foodNameEn: 'Squid', categoryId: 'cat-seafood', shelfLife: { fridge: 2, freezer: 60, fresh: 1, room: 1 }, source: 'preset' },
  { id: 'sl-85', foodName: '三文鱼', foodNameEn: 'Salmon', categoryId: 'cat-seafood', shelfLife: { fridge: 2, freezer: 60, fresh: 1, room: 1 }, source: 'preset' },
  { id: 'sl-86', foodName: '带鱼', foodNameEn: 'Hairtail', categoryId: 'cat-seafood', shelfLife: { fridge: 2, freezer: 60, fresh: 1, room: 1 }, source: 'preset' },
  { id: 'sl-87', foodName: '海参', foodNameEn: 'Sea Cucumber', categoryId: 'cat-seafood', shelfLife: { fridge: 3, freezer: 90, fresh: 2, room: 1 }, source: 'preset' },
  // 乳制品
  { id: 'sl-90', foodName: '牛奶', foodNameEn: 'Milk', categoryId: 'cat-dairy', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 1 }, source: 'preset' },
  { id: 'sl-91', foodName: '酸奶', foodNameEn: 'Yogurt', categoryId: 'cat-dairy', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 2 }, source: 'preset' },
  { id: 'sl-92', foodName: '奶酪', foodNameEn: 'Cheese', categoryId: 'cat-dairy', shelfLife: { fridge: 14, freezer: 60, fresh: 7, room: 3 }, source: 'preset' },
  { id: 'sl-93', foodName: '黄油', foodNameEn: 'Butter', categoryId: 'cat-dairy', shelfLife: { fridge: 21, freezer: 90, fresh: 14, room: 3 }, source: 'preset' },
  { id: 'sl-94', foodName: '奶油', foodNameEn: 'Cream', categoryId: 'cat-dairy', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 2 }, source: 'preset' },
  // 饮品
  { id: 'sl-100', foodName: '果汁', foodNameEn: 'Juice', categoryId: 'cat-drink', shelfLife: { fridge: 7, freezer: 30, fresh: 5, room: 2 }, source: 'preset' },
  { id: 'sl-101', foodName: '豆浆', foodNameEn: 'Soy Milk', categoryId: 'cat-drink', shelfLife: { fridge: 3, freezer: 30, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-102', foodName: '啤酒', foodNameEn: 'Beer', categoryId: 'cat-drink', shelfLife: { fridge: 180, freezer: 0, fresh: 90, room: 90 }, source: 'preset' },
  { id: 'sl-103', foodName: '红酒', foodNameEn: 'Red Wine', categoryId: 'cat-drink', shelfLife: { fridge: 180, freezer: 0, fresh: 90, room: 90 }, source: 'preset' },
  { id: 'sl-104', foodName: '可乐', foodNameEn: 'Cola', categoryId: 'cat-drink', shelfLife: { fridge: 180, freezer: 30, fresh: 90, room: 90 }, source: 'preset' },
  { id: 'sl-105', foodName: '矿泉水', foodNameEn: 'Mineral Water', categoryId: 'cat-drink', shelfLife: { fridge: 365, freezer: 0, fresh: 180, room: 365 }, source: 'preset' },
  // 调味品
  { id: 'sl-110', foodName: '酱油', foodNameEn: 'Soy Sauce', categoryId: 'cat-sauce', shelfLife: { fridge: 180, freezer: 0, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-111', foodName: '醋', foodNameEn: 'Vinegar', categoryId: 'cat-sauce', shelfLife: { fridge: 180, freezer: 0, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-112', foodName: '蚝油', foodNameEn: 'Oyster Sauce', categoryId: 'cat-sauce', shelfLife: { fridge: 90, freezer: 0, fresh: 60, room: 30 }, source: 'preset' },
  { id: 'sl-113', foodName: '番茄酱', foodNameEn: 'Ketchup', categoryId: 'cat-sauce', shelfLife: { fridge: 90, freezer: 0, fresh: 60, room: 30 }, source: 'preset' },
  { id: 'sl-114', foodName: '沙拉酱', foodNameEn: 'Salad Dressing', categoryId: 'cat-sauce', shelfLife: { fridge: 60, freezer: 0, fresh: 30, room: 14 }, source: 'preset' },
  { id: 'sl-115', foodName: '辣椒酱', foodNameEn: 'Chili Sauce', categoryId: 'cat-sauce', shelfLife: { fridge: 90, freezer: 0, fresh: 60, room: 30 }, source: 'preset' },
  { id: 'sl-116', foodName: '豆瓣酱', foodNameEn: 'Bean Paste', categoryId: 'cat-sauce', shelfLife: { fridge: 90, freezer: 0, fresh: 60, room: 30 }, source: 'preset' },
  { id: 'sl-117', foodName: '芝麻酱', foodNameEn: 'Sesame Paste', categoryId: 'cat-sauce', shelfLife: { fridge: 60, freezer: 0, fresh: 30, room: 14 }, source: 'preset' },
  // 熟食/剩菜
  { id: 'sl-120', foodName: '剩饭', foodNameEn: 'Leftover Rice', categoryId: 'cat-cooked', shelfLife: { fridge: 3, freezer: 30, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-121', foodName: '剩菜', foodNameEn: 'Leftover Dish', categoryId: 'cat-cooked', shelfLife: { fridge: 3, freezer: 30, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-122', foodName: '饺子', foodNameEn: 'Dumplings', categoryId: 'cat-cooked', shelfLife: { fridge: 3, freezer: 60, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-123', foodName: '包子', foodNameEn: 'Steamed Buns', categoryId: 'cat-cooked', shelfLife: { fridge: 3, freezer: 60, fresh: 2, room: 1 }, source: 'preset' },
  { id: 'sl-124', foodName: '蛋糕', foodNameEn: 'Cake', categoryId: 'cat-cooked', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-125', foodName: '披萨', foodNameEn: 'Pizza', categoryId: 'cat-cooked', shelfLife: { fridge: 3, freezer: 30, fresh: 2, room: 1 }, source: 'preset' },
  // 冷冻食品
  { id: 'sl-130', foodName: '速冻水饺', foodNameEn: 'Frozen Dumplings', categoryId: 'cat-frozen', shelfLife: { fridge: 1, freezer: 90, fresh: 0, room: 0 }, source: 'preset' },
  { id: 'sl-131', foodName: '冰淇淋', foodNameEn: 'Ice Cream', categoryId: 'cat-frozen', shelfLife: { fridge: 0, freezer: 90, fresh: 0, room: 0 }, source: 'preset' },
  { id: 'sl-132', foodName: '冷冻薯条', foodNameEn: 'Frozen Fries', categoryId: 'cat-frozen', shelfLife: { fridge: 1, freezer: 90, fresh: 0, room: 0 }, source: 'preset' },
  { id: 'sl-133', foodName: '冷冻蔬菜', foodNameEn: 'Frozen Vegetables', categoryId: 'cat-frozen', shelfLife: { fridge: 1, freezer: 90, fresh: 0, room: 0 }, source: 'preset' },
  // 面食/烘焙
  { id: 'sl-140', foodName: '面包', foodNameEn: 'Bread', categoryId: 'cat-bakery', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 3 }, source: 'preset' },
  { id: 'sl-141', foodName: '面条', foodNameEn: 'Noodles', categoryId: 'cat-bakery', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 7 }, source: 'preset' },
  { id: 'sl-142', foodName: '馒头', foodNameEn: 'Steamed Bread', categoryId: 'cat-bakery', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-143', foodName: '饼干', foodNameEn: 'Biscuits', categoryId: 'cat-bakery', shelfLife: { fridge: 0, freezer: 0, fresh: 0, room: 90 }, source: 'preset' },
  { id: 'sl-144', foodName: '月饼', foodNameEn: 'Mooncake', categoryId: 'cat-bakery', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 14 }, source: 'preset' },
  // 蛋类
  { id: 'sl-150', foodName: '鸡蛋', foodNameEn: 'Egg', categoryId: 'cat-egg', shelfLife: { fridge: 21, freezer: 0, fresh: 14, room: 7 }, source: 'preset' },
  { id: 'sl-151', foodName: '鸭蛋', foodNameEn: 'Duck Egg', categoryId: 'cat-egg', shelfLife: { fridge: 21, freezer: 0, fresh: 14, room: 7 }, source: 'preset' },
  { id: 'sl-152', foodName: '鹌鹑蛋', foodNameEn: 'Quail Egg', categoryId: 'cat-egg', shelfLife: { fridge: 14, freezer: 0, fresh: 10, room: 5 }, source: 'preset' },
  // 罐头/腌制
  { id: 'sl-160', foodName: '罐头', foodNameEn: 'Canned Food', categoryId: 'cat-canned', shelfLife: { fridge: 180, freezer: 180, fresh: 90, room: 365 }, source: 'preset' },
  { id: 'sl-161', foodName: '泡菜', foodNameEn: 'Kimchi', categoryId: 'cat-canned', shelfLife: { fridge: 30, freezer: 90, fresh: 14, room: 7 }, source: 'preset' },
  { id: 'sl-162', foodName: '咸菜', foodNameEn: 'Pickled Vegetables', categoryId: 'cat-canned', shelfLife: { fridge: 60, freezer: 90, fresh: 30, room: 14 }, source: 'preset' },
  { id: 'sl-163', foodName: '豆腐乳', foodNameEn: 'Fermented Tofu', categoryId: 'cat-canned', shelfLife: { fridge: 90, freezer: 0, fresh: 60, room: 30 }, source: 'preset' },
  // 其他
  { id: 'sl-170', foodName: '豆腐', foodNameEn: 'Tofu', categoryId: 'cat-other', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 1 }, source: 'preset' },
  { id: 'sl-171', foodName: '蜂蜜', foodNameEn: 'Honey', categoryId: 'cat-other', shelfLife: { fridge: 365, freezer: 0, fresh: 180, room: 365 }, source: 'preset' },
  { id: 'sl-172', foodName: '巧克力', foodNameEn: 'Chocolate', categoryId: 'cat-other', shelfLife: { fridge: 90, freezer: 180, fresh: 60, room: 60 }, source: 'preset' },
  { id: 'sl-173', foodName: '坚果', foodNameEn: 'Nuts', categoryId: 'cat-other', shelfLife: { fridge: 60, freezer: 180, fresh: 30, room: 30 }, source: 'preset' },
  { id: 'sl-174', foodName: '干果', foodNameEn: 'Dried Fruits', categoryId: 'cat-other', shelfLife: { fridge: 60, freezer: 180, fresh: 30, room: 60 }, source: 'preset' },
  { id: 'sl-175', foodName: '茶叶', foodNameEn: 'Tea', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-176', foodName: '咖啡', foodNameEn: 'Coffee', categoryId: 'cat-other', shelfLife: { fridge: 90, freezer: 180, fresh: 60, room: 60 }, source: 'preset' },
  { id: 'sl-177', foodName: '米饭(生)', foodNameEn: 'Rice (Raw)', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-178', foodName: '面粉', foodNameEn: 'Flour', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 90 }, source: 'preset' },
  { id: 'sl-179', foodName: '酵母', foodNameEn: 'Yeast', categoryId: 'cat-other', shelfLife: { fridge: 30, freezer: 90, fresh: 14, room: 7 }, source: 'preset' },
  // 粗粮/杂粮类
  { id: 'sl-300', foodName: '糙米', foodNameEn: 'Brown Rice', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-301', foodName: '燕麦', foodNameEn: 'Oats', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-302', foodName: '小米', foodNameEn: 'Millet', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-303', foodName: '红豆', foodNameEn: 'Red Beans', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-304', foodName: '绿豆', foodNameEn: 'Mung Beans', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-305', foodName: '黑豆', foodNameEn: 'Black Beans', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-306', foodName: '薏米', foodNameEn: 'Barley', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-307', foodName: '荞麦', foodNameEn: 'Buckwheat', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-308', foodName: '玉米碴', foodNameEn: 'Corn Grits', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-309', foodName: '红薯', foodNameEn: 'Sweet Potato', categoryId: 'cat-vegetable', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 7 }, source: 'preset' },
  { id: 'sl-310', foodName: '紫薯', foodNameEn: 'Purple Sweet Potato', categoryId: 'cat-vegetable', shelfLife: { fridge: 14, freezer: 30, fresh: 7, room: 7 }, source: 'preset' },
  { id: 'sl-311', foodName: '玉米', foodNameEn: 'Corn', categoryId: 'cat-vegetable', shelfLife: { fridge: 5, freezer: 30, fresh: 3, room: 2 }, source: 'preset' },
  { id: 'sl-312', foodName: '花生', foodNameEn: 'Peanuts', categoryId: 'cat-other', shelfLife: { fridge: 60, freezer: 180, fresh: 30, room: 30 }, source: 'preset' },
  { id: 'sl-313', foodName: '莲子', foodNameEn: 'Lotus Seeds', categoryId: 'cat-other', shelfLife: { fridge: 180, freezer: 365, fresh: 90, room: 180 }, source: 'preset' },
  { id: 'sl-314', foodName: '红枣', foodNameEn: 'Red Dates', categoryId: 'cat-fruit', shelfLife: { fridge: 30, freezer: 180, fresh: 14, room: 14 }, source: 'preset' },
  { id: 'sl-315', foodName: '桂圆', foodNameEn: 'Dried Longan', categoryId: 'cat-other', shelfLife: { fridge: 60, freezer: 180, fresh: 30, room: 60 }, source: 'preset' },
  { id: 'sl-316', foodName: '枸杞', foodNameEn: 'Goji Berries', categoryId: 'cat-other', shelfLife: { fridge: 60, freezer: 180, fresh: 30, room: 60 }, source: 'preset' },
];
